### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-olzzon-ndicontroller#1]
@olzzon 

You need a build script like https://github.com/bitfocus/companion-module-behringer-x32/blob/master/package.json#L19, so that companion can compile the typescript. It needs to be using npx, because the devDependencies won't be installed.
You can probably test it by deleting the node_modules folder and running `yarn --prod` 

https://github.com/bitfocus/companion-module-olzzon-ndicontroller/blob/main/src/Companion/feedback.ts#L29-L34 I would simplify this block to `return feedback.options.srcNumber === selectedsource` setting values on options here is strange, and will probably fail in future companion versions. I also dont see any need to cache the check like that?

It feels like this file https://github.com/bitfocus/companion-module-olzzon-ndicontroller/blob/main/src/NdiController/ndiControllerClient.ts#L9-L12 should be a class. Using globals like this will cause issues if someone tries to use multiple instances of the module, as they will be sharing the values of these variables

**Comment by olzzon** [comment]
@Julusian 
Thanks a lot. I have:
* Added build script
* simplified the feedback
* refactored the ndiController part to a Class

**Comment by Julusian** [comment]
Looks good
